### ISSUE TITLE
vue3 vite.config.js 方式 问下这个文件 _pkg_load_.js是哪来的？ 

### ISSUE THREAD

**Issue by w123angmeng** [zionLZH/zion-uniapp-mp-load-package#1]
===加载出错 xxx/_pkg_load_.js module 'xxx/_pkg_load_.js' is not defined, require args is 'xxx/_pkg_load_.js'

**Comment by zionLZH** [comment]
这是不存在的，是插件中自己生成的，因为插件不能准确知道uni打包出来的分包，因此会先遍历pages.json中配置的subpackages，给每个subpackage写入一个pkg_load.js问题，用于加载分包（这是微信官方的限制，必须是加载某个分包成功之后才可以加载里面的js），如果出现问题可以加我qq 1740018855，但是一般按照demo是不会有太大问题
