### ISSUE TITLE
vue2 loadMpPackageModule

### ISSUE THREAD

**Issue by iilitlleboyii** [zionLZH/zion-uniapp-mp-load-package#2]
微信开发者工具 version: Stable 1.06.2405020
HBuilderX version: 4.23

loadMpPackageModule表现有问题：第一次调用时会报错Cannot read property 'call' of undefined，并且引用依赖文件导出对象一直是空对象{}
![image](https://github.com/user-attachments/assets/d666a320-64d0-4d5c-90be-c1b19b5aa325)

**Comment by zionLZH** [comment]
晚点联系qq 174001885，现在在上班没法看TAT

**Comment by zionLZH** [comment]
> 微信开发者工具 version: Stable 1.06.2405020 HBuilderX version: 4.23
> 
> loadMpPackageModule表现有问题：第一次调用时会报错Cannot read property 'call' of undefined，并且引用依赖文件导出对象一直是空对象{} ![image](https://private-user-images.githubusercontent.com/103729103/350875698-d666a320-64d0-4d5c-90be-c1b19b5aa325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTUxNDUsIm5iZiI6MTcyMTY1NDg0NSwicGF0aCI6Ii8xMDM3MjkxMDMvMzUwODc1Njk4LWQ2NjZhMzIwLTY0ZDAtNGQ1Yy05MGJlLWMxYjE5YjVhYTMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMzI3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTBjYjViZmYwODVlZGY5MTIxZDIwYzllNjQ3MzkyZjZiNjljYmI1NzYyYjg1YjBkZmFmZDZmNjZlOTQzZjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bRkGQ7p4sDV7OyNaZG75zAxAUNkjss30LZWljeIJaFs)

麻烦加一下qq，大概知道是window下的问题了

**Comment by zionLZH** [comment]
已经修复 ([77cef93](https://github.com/zionLZH/zion-uniapp-mp-load-package/commit/77cef93b69b1bd468bb28a6685e06ec75656e88b))
