### ISSUE TITLE
引入插件，未曾做任何分包异步化配置，主包增大

### ISSUE THREAD

**Issue by dyywork** [zionLZH/zion-uniapp-mp-load-package#3]
![image](https://github.com/user-attachments/assets/e839aec2-096d-4fd9-a7c8-a00f7ac2b621)
为引入插件前主包分包大小
![image](https://github.com/user-attachments/assets/8f8768f5-1ceb-4dbc-9038-67fe850597c6)
引入插件未做任何分包异步化配置，只是引入插件后预览的主包和分包大小，

主包多了近500kb

**Comment by zionLZH** [comment]
不存在的，加qq 1740018855

**Comment by zionLZH** [comment]
已经确定有该bug，仅存在vue2版本，目前针对性处理，但是见效不大
